name: Deploy to Server

on:
  push:
    branches: [ main ]  # 当推送到main分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    # 登录到Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # 构建并推送Docker镜像
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/card-store:latest
    
    # 部署到服务器
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # 拉取最新的镜像
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/card-store:latest
          
          # 停止并删除旧容器
          docker stop card-store || true
          docker rm card-store || true
          
          # 运行新容器
          docker run -d \
            --name card-store \
            -p 80:80 \
            --restart always \
            ${{ secrets.DOCKERHUB_USERNAME }}/card-store:latest 